apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  labels:
    
    app: springapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
        - name: springapp
          image: public.ecr.aws/q0r5o2b3/k8s-deploy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
