apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name:  newspringapp
  labels:
    
    app: newspringapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: newspringapp
  template:
    metadata:
      labels:
        app: newspringapp
    spec:
      containers:
        - name: newspringapp
          image: public.ecr.aws/q0r5o2b3/k8s-deploy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
