apiVersion: apps/v1
kind: Deployment
metadata:
  name: Newspringapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Newspring-app
  template:
    metadata:
      labels:
        app: Newspring-app
    spec:
      containers:
        - name: Newspringapp-deployment
          image: public.ecr.aws/n0o1i7t6/sakthi-new:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
              
# service type loadbalancer

apiVersion: v1
kind: Service
metadata:
  name: New-springapp
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: Newspring-app
