apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapplication
  labels:
    app: springapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapplication
  template:
    metadata:
      labels:
        app: springapplication
    spec:
      containers:
        - name: springapplication
          image: k8s-deploy:latest public.ecr.aws/p5c8a2k9/k8s-deploy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          
