apiVersion: apps/v1
kind: Deployment
metadata:
  name:  newspringapp-deployments
  labels:
    app: newspringapp-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newspringapp-deployments
  template:
    metadata:
      labels:
        app: newspringapp-deployments
    spec:
      containers:
        - name: newspringapp-deployments
          image: public.ecr.aws/q0r5o2b3/k8s-deploy:latest
          imagePullPolicy: Always
          ports:
            - containerPort:  8080
