apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
  labels:
    app: my-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
    spec:
      containers:
        - name: my-application
          image: k8s-deploy:latest public.ecr.aws/p5c8a2k9/k8s-deploy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
