apiVersion: apps/v1
kind: Deployment
metadata:
  name: newspringapp-deploy
  labels:
    app: newspringapp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newspringapp-deploy
  template:
    metadata:
      labels:
        app: newspringapp-deploy
    spec:
      containers:
        - name: newspringapp-deploy
          image: public.ecr.aws/q0r5o2b3/new_job:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

