apiVersion: apps/v1
kind: Deployment
metadata:
  name: Newspringapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Newspring-app
  template:
    metadata:
      labels:
        app: Newspring-app
    spec:
      containers:
      - name: Newspringapp
        image: 211223789150.dkr.ecr.us-east-2.amazonaws.com/my-springboot-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: Newspringapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: Newspring-app
