apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  labels:
    app: spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: public.ecr.aws/q0r5o2b3/k8s-deploy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
