apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: Newspringapp
  name: Newspringapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Newspringapp
  template:
    metadata:
      labels:
        app: Newspringapp
    spec:
      containers:
      - name: my-springboot-app
        image: 211223789150.dkr.ecr.us-east-2.amazonaws.com/my-springboot-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: Newspringapp
    k8s-app: Newspringapp
  name: Newspringapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app
